name: Release Please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          config-file: .release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          
      # The deployment workflow will only trigger if a new release was created
      - name: Trigger deploy workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy