name: Release Please

on:
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    # Only run when PRs are merged, not just closed
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          config-file: .release-please-config.json
          manifest-file: .github/release-please.yml
          default-branch: main
          
      # Only run deployment if a new release was created
      - name: Trigger deploy workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy