name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write  # Needed for label creation

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4 # Use the latest major version from googleapis
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # Only run the following steps if a release was created
      - name: Checkout 🛎️
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
          
      # Trigger deploy workflow after release is created
      - name: Trigger deploy workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy